### ISSUE TITLE
yarn start results in ENOSPC

### ISSUE THREAD

**Issue by povilasb** [joshuef/webIdManager#17]
# Problem

`ENOSPC` - error no space left

When I do `yarn start` I get an infinite flow of errors:
```
Error: watch /home/povilas/maidsafe/safe-apps/webIdManager/node_modules/snapdragon-node/node_modules ENOSPC
    at _errnoException (util.js:1041:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:232:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:414:19)
    at FSWatcher.<anonymous> (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:462:19)
    at FSWatcher.<anonymous> (/home/povilas/maidsafe/safe-apps/webIdManager/node_modules/chokidar/lib/nodefs-handler.js:467:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

# Environment

Linux: 
```
$ cat /etc/issue
Debian GNU/Linux 9 \n \l

$ uname -a
Linux povilasb 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

$ df -h      
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           788M  9.2M  778M   2% /run
/dev/sda1       114G   97G   11G  90% /
tmpfs           3.9G  254M  3.6G   7% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           788M   12K  788M   1% /run/user/1000
```

JavaScript:
```
$ nvm current
v8.11.3

$ yarn --version
1.7.0
```

**Comment by joshuef** [comment]
@povilasb looks like you're reaching a limit on file watching (due to nodejs/npm doing a lot of watching with the dependencies).

You can fix that: https://stackoverflow.com/questions/22475849/node-js-error-enospc

Or, optionally run `yarn build` in the project to get the full `dist` folder, which you can then serve locally via your preferred http server.

**Comment by povilasb** [comment]
cool, that worked, thx :)
